### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [RipperHybrid/AshLooper#1]
May I ask what license you've chosen for your module – and whether the source of the Volume-Ke-Selector is available under a FOSS license, too? Thanks in advance!

**Comment by RipperHybrid** [comment]
Hi, 
Thank you for your interest in the module. Currently, I haven't specified a license for the module. I will look into choosing an appropriate open-source license soon.Regarding the Volume Key Selector, it's a binary created by someone else. Its details are mentioned in the install.sh script under the Volume Key Selector folder

**Comment by IzzySoft** [comment]
Thanks for the fast response! Asking because I thought your module could be added to [this repo](https://apt.izzysoft.de/magisk) which only accepts FOSS modules, so it needs a license and the source code available. Waiting for your choice then, thanks!

**Comment by RipperHybrid** [comment]
> Thanks for the fast response! Asking because I thought your module could be added to [this repo](https://apt.izzysoft.de/magisk) which only accepts FOSS modules, so it needs a license and the source code available. Waiting for your choice then, thanks!

Hi IzzySoft,

Thank you for your interest. Yes, you can add my module to the repository. I'm pleased to see it included in your collection of modules.

If you need any further information or assistance, please let me know.

Thanks!

**Comment by IzzySoft** [comment]
Thanks! I've added it now. But it seems I'll need to override the description given by the module itself:

![image](https://github.com/user-attachments/assets/62f735d4-3026-4f11-bfbf-9f787c8a9778)

Done that now, so I hope this is OK for you:

![image](https://github.com/user-attachments/assets/5020120a-153f-473e-ac1e-38ef379138c1)

It's just for the display in the repo, I of course didn't alter the ZIP.

> Regarding the Volume Key Selector, it's a binary created by someone else. Its details are mentioned in the install.sh script under the Volume Key Selector folder

Going from the Readme, I can find its repo linked, thanks! Digging in there a bit I find it seems to be covered by the Apache-2.0 license (you might wish to mention that with your corresponding Readme), so all should be fine. It's already live at the IzzyOnDroid Magisk repo now. Thanks a lot again – and welcome aboard!

(PS: As you might wonder about the "only" in "GPL-3.0-only": that just means "not including or-later", which can be done optionally. It's totally fine the way it is as it gives you the chance to decide on "later" when it becomes available – and not having to apply "blind trust". Many of my projects are GPL-2.0-only even, for "reasons" :stuck_out_tongue_winking_eye:)
